### ISSUE TITLE
the maker doesn't work

### ISSUE THREAD

**Issue by vatsal6pro** [Draguisada/Demon-slayer-datapack-download#8]
I put everything in the maker and then waited 24 mins. the only thing i did not do was right click the sun thingy, But was that needed? Please fix this i have to put the datapack in my server

**Comment by Draguisada** [comment]
Oh hello, this thing is kinda dead a while, but yes i've got it fix already, just didn't updated.
Not saying that this datapack is dead or i'm never going to update again, but it's kinda rare to I continue untill the last season.
Going to update soon! Just check everything!

**Comment by vatsal6pro** [comment]
Okay... @Draguisada I need you to contact me on discord KingCat#6852
It's a real important thing...
